import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { VolumeConfigProvider } from "./context/VolumeConfigContext";
import { headers } from "next/headers";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    const headersList = await headers();
    // Databricks Apps forwards the original path via x-forwarded-prefix
    const basePath = headersList.get("x-forwarded-prefix") ?? "";

    return (
        <html lang="en">
        <head>
            <meta name="app-base-path" content={basePath} />
        </head>
        <body>
        <VolumeConfigProvider>
            {children}
        </VolumeConfigProvider>
        </body>
        </html>
    );
}
